version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.15
workflows:
  build-and-test:
    jobs:
      - shellcheck/check
      - run-unit-tests
jobs:
  run-unit-tests:
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run unit tests
          command: make docker-unit-test
