version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.16
jobs:
  unit-test-heroku-stack:
    parameters:
      stack:
        type: "string"
        default: "heroku-20"
    docker:
      - image: "danielleadams/shpec-<<parameters.stack>>:latest"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Shpec unit tests on <<parameters.stack>>
          command: make unit-test
workflows:
  version: 2
  run-tests:
    jobs:
      - unit-test-heroku-stack:
          name: "Unit tests for heroku-20"
          stack: "heroku-20"
      - unit-test-heroku-stack:
          name: "Unit tests for heroku-18"
          stack: "heroku-18"
      - unit-test-heroku-stack:
          name: "Unit tests for heroku-16"
          stack: "heroku-16"
      - shellcheck/check
